inst/tutorials/02-data-visualization/tutorial.Rmd
=> Anish work

inst/tutorials/02-data-visualization/tutorial.Rmd
Small Changes to the format to the tutorial
=> Chapter 2 Tutorial Edits

inst/tutorials/10-layers/tutorial.Rmd
Chapter 10 updates, now include sections as follows:
**10.1 Introduction**
Our introduction
**10.2 Aesthetic Mappings**
Aesthetic Mappings: Simple geom_point()
Aesthetic Mappings: Advanced geom_point()
**10.3 Geometric Objects**
Geometric Objects with geom_smooth()
Geometric Objects with geom_histogram() and geom_boxplot()
Geometric Objects with geom_density()
**10.4 Facets and 10.5 Statistical Transformations**
Facets and Statistical Transformations with geom_col(), facet_wrap(), and facet_grid()
**10.5 Statistical Transformations and 10.6 Position Adjustments**
Statistical Transformations and Position Adjustments with geom_bar()
**10.7 Coordinate Systems**
Coordinate Systems
**10.8 The layered grammar of graphics**
Proper grammar of how code should be written has been covered throughout …
=> chapter 10 updates

inst/tutorials/10-layers/tutorial.Rmd
Cleaned up chapter 10 to include more knowledge drops and cleaned up any possible bugs or formatting issues. Removed and added sentences to make it easier for students to understand and included any other fixes to exercises and subchapters within chapter 10.
=> cleaned up chapter 10

inst/tutorials/15-strings/tutorial.Rmd
=> chapter 15

inst/tutorials/15-strings/tutorial.Rmd
all sections finished just need some fixes in sentences and clear unwanted sentences, but didn't finish non English characters since i kept getting error when try to run the code in book myself.
=> chapter 15 done but one catch

TODO.txt, inst/tutorials/20-joins/tutorial.Rmd
The layout is done, will be adding exercises now
=> chapter 20 

inst/tutorials/10-layers/tutorial.Rmd
chapter 10 is all up to date now with all of the book material, tutorials, and fixes.
=> small fixes to chapter 10 

inst/tutorials/18-dates-and-times/tutorial.Rmd
18.1 
Introduction
18.2
Creating date/times through import
Creating date/times with strings
Creating date/times with individual components
Date-time components with getting components
18.3
Date-time components with rounding
Date-time components with modifying components
18.6
Summary
Besides 18.4 and 18.5 everything else has been added to the tutorial
=> chapter 18 updates

inst/tutorials/20-joins/tutorial.Rmd
choater 20 one more section almost done
=> almost done with another section

inst/tutorials/10-layers/tutorial.Rmd
-Geometric Objects with `geom_density()` is now removed
-Facets and Statistical Transformations with `geom_col()`, `facet_wrap()`, and `facet_grid()` is now replaced with mpg data instead
-Statistical Transformations and Position Adjustments with `geom_bar()` is now replaced with midwest data instead
=> removed all trains data from chapter 10

inst/tutorials/10-layers/tutorial.Rmd
chapter 10 should all be fixed now: 
no use of `skim` package 
no use of `ggthemes` throughout the tutorial
included knowledge drop (there should now be enough knowledge drops throughout the entire chapter)
=> chapter 10 fixes to skim, themes, and knowledge drops

inst/tutorials/18-dates-and-times/tutorial.Rmd
added 18.4 section to chapter 18 tutorial:
18.4 time spans with duration
18.4 time spans with periods
18.4 time spans with interval
=> chapter 18 updates to include exercises for 18.4 time spans

inst/tutorials/12-communication/tutorial.Rmd, inst/tutorials/14-numbers/tutorial.Rmd
Ch 12 still needs a few more additions but everything is fixed
=> Clean up ch 12 and 14

inst/tutorials/18-dates-and-times/tutorial.Rmd
finished the chapter 18 tutorial to include the 18.5 section time zones. chapter 18 tutorial now includes: 18.1 Introduction, 18.2 Creating Date/Times, 18.3 Date-time Components, 18.4 Time Spans, 18.5 Time Zones, and 18.6 Summary
=> added 18.5 section, finished chapter 18

inst/tutorials/20-joins/tutorial.Rmd
finished all the sections, just need to make some grammar fixes and make the sentences clear and simple
=> chapter 20 updates

inst/tutorials/18-dates-and-times/tutorial.Rmd
made all the necessary fixes and changes to the chapter 18 tutorial. no errors should occur anymore.
=> all necessary fixes have been made to chapter 18 tutorial

inst/tutorials/22-databases/tutorial.Rmd
added part of section 22.5:
22.5.1
22.5.2
22.5.3
22.5.4
have been added
=> updates to chapter 22

inst/tutorials/22-databases/tutorial.Rmd
updates to chapter 22 - prevents the issues from before
=> changed duckdb to RSQLite to avoid previous issues

TODO.txt, inst/tutorials/24-hierarchical-data/tutorial.Rmd
just need some feedback and fixes
=> finished the 24 chapter tutorial

inst/tutorials/28-a-field-guide-to-base-R/tutorial.Rmd
Hi Preceptor. I have now correctly loaded up the r4ds.tutorials and have added 2 questions.
=> Added 2 questions (testing out PR)

TODO.txt
Hello Preceptor. This pull request was to prove that I have successfully made an edit to the TODO.txt document, as instructed.
=> Changed doc to prove my edits are successful

TODO.txt
This is the test to confirm everything is working
=> Added my name (Pranav)

inst/tutorials/28-a-field-guide-to-base-R/tutorial.Rmd, renv.lock
test pr after nuking from orbit
=> Chapter 28

inst/tutorials/13-logical-vectors/tutorial.Rmd
All changes in Comparisons section
=> Logical vector dev

TODO.txt, inst/tutorials/13-logical-vectors/tutorial.Rmd
=> Logical Vectors tutorial completed

inst/tutorials/14-numbers/tutorial.Rmd, inst/tutorials/17-factors/tutorial.Rmd
Made my final edits to the 14-numbers tutorial as discussed in yesterday's meeting.
7/26/2023: PR amended to include work done on 17-factors
=> Edits to 14-numbers

inst/tutorials/17-factors/tutorial.Rmd, inst/tutorials/20-joins/tutorial.Rmd
fixed up 17-factors and 20-joins
=> fixing typos and adding test chunks

inst/tutorials/05-rstudio-and-github/tutorial.Rmd
just need to finish up the end and add som knowledge drops
=> did most of proj 1

inst/tutorials/13-numbers/tutorial.Rmd
I think I've edited or added all the test chunks for this tutorial. I'm still working on the knowledge drops.
=> Finished Test Chunks, working on Knowledge Drops

inst/tutorials/09-layers/tutorial.Rmd
=> Minior changes

inst/tutorials/21-databases/tutorial.Rmd
=> typos and fixes for databases

inst/tutorials/17-dates-and-times/tutorial.Rmd
- made the tutorial resemble the chapter more
- commented out some exercises I felt were unnecessary
- created new ones.
=> tutorial 17 r4ds

inst/tutorials/17-dates-and-times/tutorial.Rmd
=> tutorial 17

inst/tutorials/19-joins/tutorial.Rmd
- around halfway done, will finish rest
=> tutorial 19

inst/tutorials/22-arrow/tutorial.Rmd, inst/tutorials/23-hierarchical-data/tutorial.Rmd
Jeez hierarchical is hard to spell. Also, please take a look at the note for Hierarchical Data - JSON - Exercise 15.
=> Typos and fixes in Arrow and Hierarchical Data Tutorials

inst/tutorials/27-a-field-guide-to-base-R/tutorial.Rmd
There wasn't much I needed to really change. All the exercises seemed very reasonable and helpful. There were a few typos and little errors I had to fix. I could not figure out how to get the `map(paths, readxl::read_excel)` error to go away.
=> Tutorial 27

inst/tutorials/22-arrow/tutorial.Rmd
Did not see much to change. Added a couple new exercises.
=> tutorial 22

inst/tutorials/24-web-scraping/tutorial.Rmd, inst/tutorials/25-functions/tutorial.Rmd
Pushing this quickly because there are some big issues with Tutorial 25. Please check out Web scraping, Web scraping examples, Exercise 6 (the IMDb section isn't really working). Also, please check out df1 in tutorial 25 and its associated exercise (Functions, Data frame functions, Exercise 4). Feel free to change anything.
=> Typos and fixes for Tutorial 24 and some of Tutorial 25

inst/tutorials/21-databases/tutorial.Rmd
added a couple new exercises to spread out knowledge.
=> tutorial 21

inst/tutorials/26-iteration/tutorial.Rmd, inst/tutorials/27-a-field-guide-to-base-R/tutorial.Rmd
I accidentally deleted 26 by accident when nuking from orbit oops.
=> Typos and fixes in Tutorial 26 and 27

inst/tutorials/15-regular-expressions/tutorial.Rmd
This PR adds the sections "Pattern Control", "Practice", and "Regular expressions in other places" to the tutorial as they were previously missing from the tutorial, as well as some minor big fixes here and there.
I have some concerns regarding the length of this tutorial as it was already long previously, and now it has 3 more sections, so it will be even longer.
=> Added Sections to Tutorial 15

inst/tutorials/13-numbers/tutorial.Rmd
This PR (finally!) fixes the issues with `summarize()` and later `reframe()` by replacing both of those with `mutate()` instead.
Here's why I chose to do so:
The official R4DS book uses `summarize()` throughout, and there was still knowledge to gain by using the function. I realized that with a couple added steps, `mutate()` could be used instead, and it works better to explain what's going on too as its name implies that we are messing with the data, and not pulling a summary of it (as the name of `summary()` may falsely imply. This is why I eventually settled on using `mutate()` for the exercises that needed fixing.
WARNING: I HAVE **MAJOR** CONCERNS WITH THE LENGTH OF THIS TUTORIAL!!! As of this PR, it's 3,373 lines long, which is far longer than any other tutorial that I have seen. I …
=> Final - Fixed Tutorial 13 (Numbers)

TODO.txt, inst/tutorials/02a-rstudio-and-code/tutorial.Rmd, inst/tutorials/02b-rstudio-and-quarto/images/quarto-example.txt, inst/tutorials/02b-rstudio-and-quarto/tutorial.Rmd
Let's hope it doesn't turn out like this:
https://phdcomics.com/comics.php?f=1531
=> Edit of Script 3 of Tutorial 02a  |  Edit of Tutorial 02b

inst/tutorials/05-data-tidying/tutorial.Rmd, inst/tutorials/10-exploratory-data-analysis/tutorial.Rmd
Fixed a few errors in the r4ds package based on messages on discord.
=> error fixing 1

inst/tutorials/30-ai-tutorial-test/tutorial.Rmd
Fixed stylization, answer boxes, and more content.
=> Reformatting strings and more

inst/tutorials/30-ai-tutorial-test/tutorial.Rmd
Changed questions to adhere more to guidelines. Provided example outputs with answer boxes.
=> Fixing instructions

inst/tutorials/30-ai-tutorial-test/tutorial.Rmd
Added section for numbers, edits on strings too
=> Starting numbers
